///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace git_demo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the git_demoRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("8de70c14-4897-4fde-986b-7f2746213f2c")]
    public partial class git_demoRepository : RepoGenBaseFolder
    {
        static git_demoRepository instance = new git_demoRepository();

        /// <summary>
        /// Gets the singleton class instance representing the git_demoRepository element repository.
        /// </summary>
        [RepositoryFolder("8de70c14-4897-4fde-986b-7f2746213f2c")]
        public static git_demoRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public git_demoRepository() 
            : base("git_demoRepository", "/", null, 0, false, "8de70c14-4897-4fde-986b-7f2746213f2c", ".\\RepositoryImages\\git_demoRepository8de70c14.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("8de70c14-4897-4fde-986b-7f2746213f2c")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class git_demoRepositoryFolders
    {
    }
#pragma warning restore 0436
}
